theme: jekyll-theme-hacker
title: Conception et implémentation d'un dispositif d'écoute sur WLAN
description: Samy HAMAÏDIA - Dans le cadre de l'écoute et du cyber-espionnage de réseaux et des systèmes informatiques, l'implémentation d'une solution physique est sans doute plus efficace qu'une solution logiciel sur le plan de la persistance, le contrôle et la furtivité, en s'appuyant sur des failles humaines, d'ignorance, d’insuffisance budgétaire, ressemblance d'équipements ou de défaillances orchestrées aux divers scénarios possibles, concrétisé par un mini-serveur UNIX, doté d’une panoplie d’option physique et logiciel adaptable aux circonstances, basé physiquement sur un nano-ordinateur monocarte à processeur ARM, avec la possibilité de lui fournir une connectivité et alimentation propre en plus de l'équipement en question.
url: https://samyusthb.github.io/CONCEPTION_IMPLEMENTATION_DISPOSITIF_ECOUTE_WLAN/
author:
  name: Samy HAMAÏDIA
  email: samyh.contact@gmail.com
  url: https://sites.google.com/view/samy-hamaidia/

owner: Samy HAMAÏDIA
year: 2021
